Added new phishing domains
MetaMask/eth-phishing-detect pull request #12146
Opened 2023-03-28 06:42 UTC by anishshandilya

Added new phishing domains

2023-03-28 13:13 UTC, ktian94 requested changes

2023-03-28 13:13 UTC, ktian94 commented on src/config.json
> +    "zapper-frontend-next-8h1ycrhu9-zapper-fi.vercel.app",
Remove these

2023-03-28 13:14 UTC, ktian94 commented on src/config.json
> +    "zapper-frontend-next-4uip4z44q-zapper-fi.vercel.app",
Rm

2023-03-28 13:14 UTC, ktian94 commented on src/config.json
> +    "zapper-frontend-next-o41khhhh7-zapper-fi.vercel.app",
Rm

2023-03-28 13:14 UTC, ktian94 commented on src/config.json
> +    "darksolana.com",
Rm

2023-03-30 18:35 UTC, ktian94 requested changes

2023-03-30 18:35 UTC, ktian94 commented on src/config.json
> +    "aptools.xyz",
remove

2023-03-31 03:51 UTC, legobeat requested changes
@anishshandilya Please rebase on `main` with your commits squashed, or reopen with a cleaner history.

Thanks.

2023-04-01 17:06 UTC, closed without merging