Allowlist sites 2022-02-08 to 2022-02-14
MetaMask/eth-phishing-detect pull request #6744
Opened 2022-03-01 04:23 UTC by devenblake

## metamash.co
Fixes #6487.

Not visually similar to MetaMask.

2022-03-03 17:03 UTC, ethphishingmaintainer1000 requested changes
@devenblake let's hold off on removing `smart-contract.space`. It could be that the scammer removed the site and wants to use it for another scam in the future. If we have more info in the future, we can make changes to it then

2022-03-08 07:09 UTC, ethphishingmaintainer1000 commented on src/config.json
> -    "smart-contract.space",
@devenblake it looks like this line is still here

2022-03-11 16:18 UTC, ethphishingmaintainer1000 approved these changes

2022-03-11 16:20 UTC, merged

2022-03-12 01:58 UTC, devenblake commented
Thanks for editing my change and sorry you had to - I haven't had time to get back around to this.