Support multiple phishing configurations
MetaMask/eth-phishing-detect pull request #7079
Opened 2022-04-06 12:24 UTC by Gudahtt

The phishing detector has been updated to support multiple phishing configurations. Both the configuration object and the result object have been updated to accommodate the need to identify the name of the config that the checked domain matched. Since the config and return value was already being changed, the nomenclature has been updated to replace `black/white` with `block/allow` as well, which is a change we have been meaning to make for some time.

The old configuration accepted three lists (`blacklist`, `whitelist`, and `fuzzylist`), and a `tolerance` value for the fuzzylist match.

The new configuration is an array of objects rather than an object, to accommodate multiple configurations. Each configuration option accepts three lists (`blocklist`, `allowlist`, and `fuzzylist`), `tolerance` for the fuzzylist match, and two new properties: `name` and `version`.

The `version` parameter was already used by the old configuration, but it was not required or used by the detector itself. It is now required with the new configuration, and it is returned with each match.

The new `name` parameter describes which configuration matched the origin being checked (if any). This was critical for us because it allows us to direct the user to the appropriate place when they want to dispute a blocked site.

The return value was updated to include the `name` and `version` parameters. The `type` was updated from `blacklist` to `blocklist` and from `whitelist` to `allowlist` as well.

2022-04-06 22:54 UTC, 409H requested changes
Can you please add a commit of bumping the version number of the package?

2022-04-07 15:24 UTC, Gudahtt commented
Sure, done

2022-04-07 20:57 UTC, mcmire approved these changes
The logic represented here makes sense to me. I like all of those new tests!

2022-04-19 14:39 UTC, 409H approved these changes

2022-04-19 14:39 UTC, 409H commented
LGTM!

2022-04-19 14:49 UTC, merged

2022-04-19 14:53 UTC, Gudahtt commented
>A new version of the package eth-phishing-detect (1.2.0) was published at 2022-04-19T14:51:59.572Z from
[redacted]. The shasum of this package was 11b357776b2d1b98a9ac594a1343e5184fc26bf0.

2023-01-07 00:58 UTC, 059210 reviewed
Kk

2023-02-19 06:49 UTC, jydmyk approved these changes

2025-04-14 12:04 UTC, mustafacryptolife commented on src/detector.js
> +}
#=+

2025-04-14 12:05 UTC, mustafacryptolife reviewed
#=+

2025-05-21 09:00 UTC, mustafacryptolife commented
[]()

2026-10-06 21:51 UTC, d97wd48bvn-sudo reviewed
👍