adding phishing sites to blacklist
MetaMask/eth-phishing-detect pull request #7464
Opened 2022-05-24 13:45 UTC by AlexHerman1

ZD 887559, 889573, 890767, 892732, 891823, 892718, 891780, 894017, 888756, 893398

2022-05-24 21:04 UTC, 409H approved these changes

2022-05-24 21:04 UTC, 409H requested changes
`gudecks.com` is legitimate

2022-05-24 21:06 UTC, 409H approved these changes

2022-05-24 21:07 UTC, merged

2022-05-25 08:30 UTC, AyalTech reviewed
Why staking.oxyaorigin.com was add in the blacklist. It is a legit website !

2022-05-25 19:40 UTC, TimTinkers commented
@AlexHerman1 @409H @devenblake
Why was [impostors.gg](https://impostors.gg) blacklisted? What heuristics were used to make this determination? Why isn't this in the public database? Any transparency would be much appreciated here; we are a legitimate site and you've terrified our users.